name: Trigger auto deployment for backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'apps/part3/backend/**'
    - '.github/workflows/backend-AutoDeployTrigger-7e1bc95d-ff5e-4df1-a156-525d2f97297b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: todosacr23994.azurecr.io
          username: ${{ secrets.BACKEND_REGISTRY_USERNAME }}
          password: ${{ secrets.BACKEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: todosacr23994.azurecr.io/backend:${{ github.sha }}
          file: ./apps/part3/backend/Dockerfile
          context: ./apps/part3/backend/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.BACKEND_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n backend -g todo-part3-rg --server todosacr23994.azurecr.io --username  ${{ secrets.BACKEND_REGISTRY_USERNAME }} --password ${{ secrets.BACKEND_REGISTRY_PASSWORD }}
            az containerapp update -n backend -g todo-part3-rg --image todosacr23994.azurecr.io/backend:${{ github.sha }}
